### ISSUE TITLE
Release version 0.6

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/trac-WorkflowNotificationPlugin#3]
Noted in https://github.com/trac-hacks/trac-WorkflowNotificationPlugin/commit/b6d8a48dfec91fd9c9afeafd4bc2304e6d692e84. I'd be happy to do the final steps if you think it's ready.

**Comment by rjollos** [comment]
@ejucovy I would be happy to publish the new version if you granted me maintainer rights on PyPI (username `rjollos`).

**Comment by ejucovy** [comment]
Maintainer rights granted, thank you!

**Comment by rjollos** [comment]
Thanks! Published version 0.6 in sdist and wheel formats.
